[package]
name = "cone"
version = "0.0.1"
authors = ["Phil Chen <chen.weihai@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.2"
yew = { git = "https://github.com/DenisKolodin/yew" } #, features = ["toml", "yaml", "msgpack", "cbor"] }
